# DNSC 6203 Group Project - R Code for Plotting Song Rank Correlations
# Jessica Smith, Yahui Zhou, and Andrew Nichols
# 25 November 2015

# PLEASE SET THE WORKING DIRECTORY so that this code
# can access the files that were generated by the Python code in 
# step 1 of the workflow.

# setwd("/home/vagrant/Programming_For_Analytics/Homework/Group_Project_Final")

#-----------PART 1: CORRELATION PLOTS---------------------------------

# install.packages(c('ggplot2')  # Install this if you haven't already
library(ggplot2)

#Plot #1: How do Billboard Hot 100 rankings correlate with Shazam Top 100 rankings?
df1 <- read.csv('billboardhot100_vs_shazamtop100.csv', header=T) # Read csv file into data frame
x <- df1$billboard_rank
y <- df1$shazam_rank

# Source of linear equation label on plot with r-squared coefficient: http://goo.gl/K4yh and 
# http://stackoverflow.com/questions/7549694/ggplot2-adding-regression-line-equation-and-r2-on-graph
# This code calculates equation of the line for use in the plot
lm_eqn <- function(df1){
  m <- lm(y ~ x, df1);
  eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
                   list(a = format(coef(m)[1], digits = 2), 
                        b = format(coef(m)[2], digits = 2), 
                        r2 = format(summary(m)$r.squared, digits = 3)))
  as.character(as.expression(eq));                 
}

# Plot correlation of Billboard song rank (x-axis) vs. Shazam song rank (y-axis)
s1 = 10    # Size of point labels in plot
s2 = 2     # Size of points themselves
s3 = 3     # Size of equation in plot
ggplot(df1, aes(x=billboard_rank, y=shazam_rank, label=song))+         
  geom_point(aes(color=artist), size=s2)+
  geom_text(aes(label=song, color=artist, size=s1),hjust=-0.15, vjust=0.5)+
  geom_text(aes(label=artist, color=artist, size=s1),hjust=-0.15, vjust=-.5)+
  geom_text(aes(label=paste0('(',billboard_rank,',',shazam_rank,')'), color=artist, 
                size=s1, hjust=1.3, vjust=0))+
  geom_text(x = 4, y = 22, label = lm_eqn(df1), color='blue', size=s3, parse = TRUE)+
  labs(title="Figure 2: Billboard Hot 100 vs. Shazam Top 100")+ 
  labs(x="Billboard Song Rank", y="Shazam Song Rank")+
  geom_smooth(method="lm", fullrange=TRUE, size=.5, se=TRUE, level=.95, alpha=0.18)+
  theme_bw()+
  xlim(-5, 50)+
  ylim(-5, 45)+
  theme(legend.position="none")

dev.copy(png, file="BillboardHot100_vs_ShazamTop100.png", width=700, height=700, bg="White")
dev.off()

#Plot #2: Does the shazam hit predictor accurately predict hits on the billboard hot 100?
df2 <- read.csv('shazamhitpredictor_vs_billboardhot100.csv', header=T) # Read csv file into data frame

numHits <- length(which(df2$hit==1))
numNotHits <- length(which(df2$hit==2))

hitData <- c(numHits,numNotHits)
pct <- round(hitData/sum(hitData)*100)
hitLabels <- c('Hit','Not a hit')
hitLabels <- paste(hitLabels, pct)
hitLabels <- paste(hitLabels, "%",sep="")
colors <- c("forestgreen","firebrick")
pie(hitData, labels = hitLabels, col = colors
    ,main = "Figure 3: Percent of Shazam Predicted Hits in \nBillboard Hot 100"
    ,cex = 1.5
    ,cex.main = 1.5)

dev.copy(png, file="Hit_Predictor_vs_Top_100.png", width=700, height=700, bg="White")
dev.off()

#Plot #3: Does the billboard top trending list predict future hits on the billboard hot 100?
df3 <- read.csv('billboardtoptrending_vs_billboardhot100.csv', header=T) # Read csv file into data frame

numHits <- length(which(df3$hit==1))
numNotHits <- length(which(df3$hit==2))

hitData <- c(numHits,numNotHits)
pct <- round(hitData/sum(hitData)*100)
hitLabels <- c('Hit','Not a hit')
hitLabels <- paste(hitLabels, pct)
hitLabels <- paste(hitLabels, "%",sep="")
colors <- c("forestgreen","firebrick")
pie(hitData, labels = hitLabels, col = colors
    ,main = "Figure 4: Percent of Billboard Top Trending in \nBillboard Hot 100"
    ,cex = 1.5
    ,cex.main = 1.5)
dev.copy(png, file="Top_Trending_vs_Top_100.png", width=700, height=700, bg="White")
dev.off()

#-----------PART 2: MAP OF ARTISTS' HOMETOWNS-----------------------------
library(ggmap)
# Need list of singers and their hometowns
mydata = read.csv("location.csv", header=FALSE, stringsAsFactors=FALSE)
locn <- mydata$V2
locn_coords <- geocode(locn, source="google")
where.df <- data.frame(locn=mydata$V1)
myLocs <- data.frame(where.df, locn_coords)

# Get the map
mp <- NULL
mapWorld <- borders("world", colour="gray50", fill="gray50", boundary=TRUE)
mp <- ggplot() + mapWorld

# Layer the cities on top
mp <- mp+ geom_point(data = myLocs, aes(x=lon, y=lat, colour
                                        = locn), jitter=TRUE, size=4,
                     alpha=0.8) 
mp

dev.copy(png, file="Artist_Map.png", width=850, height=600, bg="White")
dev.off()